language: python
sudo: false
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
# commands to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=tidy tidy
  - pep8 tidy
  - pylint --reports=n tidy || true
  - pyflakes tidy
after_script:
  - coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
addons:
  apt:
    packages:
    - libtidy-0.99-0
