sudo: false
language: python
dist: bionic
python:
  - "2.7"
  - "3.6"
  - "3.7"
# commands to install dependencies
install:
  - if [ -n "$TIDY" ] ; then ./scripts/install-tidy.sh $TIDY ; fi
  - export LD_LIBRARY_PATH=`pwd`/tidy-source/build/cmake/
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=tidy tidy
  - pycodestyle tidy setup.py
  - pylint --reports=n tidy setup.py || true
  - pyflakes tidy setup.py
  - flake8 tidy setup.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  include:
    - python: "3.7"
      env: TIDY=5.7.28
    - python: "3.7"
      env: TIDY=5.4.0
    - python: "3.7"
      env: TIDY=5.2.0
    - python: "3.7"
      env: TIDY=5.0.0
    - python: "3.7"
      env: TIDY=
env:
  matrix:
    - TIDY=5.6.0
addons:
  apt:
    packages:
    - libtidy5
    - cmake
cache: pip
