sudo: false
language: python
python:
  - "2.7"
  - "pypy"
# commands to install dependencies
install:
  - if [ -n "$TIDY" ] ; then ./install-tidy.sh $TIDY ; fi
  - export LD_LIBRARY_PATH=`pwd`/tidy-source/build/cmake/
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=tidy tidy
  - pep8 tidy
  - pylint --reports=n tidy || true
  - pyflakes tidy
after_script:
  - coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - dist: xenial
      sudo: required
      python: "3.7"
  include:
    - dist: xenial
      sudo: required
      python: "3.7"
env:
  matrix:
    - TIDY=5.6.0
    - TIDY=5.4.0
    - TIDY=5.2.0
    - TIDY=5.0.0
    - TIDY=
addons:
  apt:
    packages:
    - libtidy-0.99-0
    - cmake
cache: pip
