language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git libtidy-0.99-0
# commands to install dependencies
install: 
  - pip install -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=tidy
  - pep8 tidy
  - pylint --reports=n tidy || true
  - pyflakes tidy
after_success:
  - coveralls
